"$schema" = "./node_modules/wrangler/config-schema.json"

name = "test-better-auth-worker"
compatibility_date = "2026-08-04"
main = "./src/server.ts"

[observability]
enabled = true

[assets]
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
