set dotenv-load := true

lint:
    cargo clippy --all-targets -- -D warnings && cargo fmt --check

lint-fix:
    cargo clippy --fix --allow-dirty --allow-staged && cargo fmt

typecheck:
    cargo check

test:
    cargo test

get-aoc-input *args:
    cargo run -- {{args}}
