version: "3"

tasks:
  lint:
    cmds:
      - go vet ./...
      - test -z "$(gofmt -l .)"

  "lint:fix":
    cmds:
      - gofmt -w .

  typecheck:
    cmds:
      - go build ./...

  test:
    cmds:
      - go test ./...

  get-aoc-input:
    dotenv: ['.env']
    cmds:
      - go run ./cmd/aoc {{.CLI_ARGS}}
